In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
train = pd.read_csv(r'E:\Codes\ML\ML.ai Hackathon\data\train_games.csv')
train.head(10)

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs,publisher_is_developer,internal_build_id,marketing_campaign_type,day_one_patch_size_mb
0,G000019,Night in the Saga,Atari 2600,Console,Atari,2,Adventure,1985,Take-Two Interactive,Raw Fury,...,0,0,0,0,16.5,72.7,0,E571DCF3,NaN,7534
1,G000129,Metal Gear Legend,Atari 2600,Console,Atari,2,Idle/Clicker,1985,Nintendo,Larian Studios,...,0,0,0,0,10.6,44.5,0,DA796E03,Campaign_C,13313
2,G000192,FIFA 2024,NES,Console,Nintendo,3,Sports,1985,FromSoftware,Activision Blizzard,...,0,0,0,0,14.0,63.1,0,7C30DA4B,Campaign_C,11487
3,G000200,Tales of World,NES,Console,Nintendo,3,Role-Playing,1985,Ubisoft,Toby Fox,...,0,0,0,0,66.2,152.1,0,D75B1F62,NaN,12498
4,G000254,God of Shadow,PC,PC,Various,0,Action,1985,Nintendo,Nintendo,...,0,0,0,0,10.4,27.4,1,049CF258,Campaign_B,1917
5,G000383,Call of Duty: New Dawn,PC,PC,Various,0,Shooter,1985,2K Games,2K Games,...,0,0,0,0,7.9,23.5,1,823DD072,NaN,7003
6,G000417,PGA Tour 2026,NES,Console,Nintendo,3,Sports,1985,CD Projekt,CD Projekt,...,0,0,0,0,18.2,65.7,1,80BB6B6A,NaN,5170
7,G000458,Counter-Strike 3,Atari 2600,Console,Atari,2,Shooter,1985,Bethesda Softworks,Annapurna Interactive,...,0,0,0,0,14.0,32.7,0,D8AD143F,Campaign_C,13050
8,G000524,Tetris Origins,NES,Console,Nintendo,3,Puzzle,1985,Epic Games,Klei Entertainment,...,0,0,0,0,11.1,26.5,0,52D6ED59,NaN,2126
9,G000546,Iron Odyssey,PC,PC,Various,0,Platform,1985,Electronic Arts,Sony Interactive,...,0,0,0,0,12.4,33.5,0,FA73EAB2,Campaign_A,11853

In [5]:
test = pd.read_csv(r'E:\Codes\ML\ML.ai Hackathon\data\test_features.csv')
test.head(10)

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs,publisher_is_developer,internal_build_id,marketing_campaign_type,day_one_patch_size_mb
0,G016973,World of Warcraft: Eternal,Mobile (Android),Mobile,Google,0,MMORPG,2024,Double Fine,Double Fine,...,0,0,0,0,179.1,843.6,1,AFC3DF21,Campaign_C,2770
1,G011036,Counter-Strike : Redux,Mobile (Android),Mobile,Google,0,Shooter,2023,Unknown Worlds,Unknown Worlds,...,1,0,0,0,6.1,17.8,1,488E1537,Campaign_A,10980
2,G000593,Euro Truck Simulator 2,PC,PC,Various,0,Simulation,2021,Devolver Digital,Devolver Digital,...,0,0,0,0,13.2,61.4,1,40541EDB,Campaign_A,12403
3,G013281,Rise of the Reborn,Stadia,Streaming,Google,9,Action,2023,Remedy Entertainment,Remedy Entertainment,...,0,0,0,0,10.1,27.2,1,BAF5660F,Campaign_C,14374
4,G004160,Professor Layton and the Saga,PlayStation 4,Console,Sony,8,Puzzle,2023,Double Fine,Double Fine,...,0,0,0,0,8.4,21.5,1,21D7C371,Campaign_A,5114
5,G021184,UFC 6,Mobile (Android),Mobile,Google,0,Sports,2024,Epic Games,Other,...,0,0,0,0,22.8,64.7,0,8397832F,NaN,4837
6,G010351,Doom Origins,Xbox One,Console,Microsoft,8,Action,2020,2K Games,Microsoft Studios,...,0,0,0,0,19.6,69.4,0,9ECF9B4F,NaN,1603
7,G029863,F1 2025,Nintendo Switch,Hybrid,Nintendo,9,Sports,2023,Sega,Double Fine,...,0,0,0,0,20.2,76.2,0,94DEE4C2,Campaign_A,11203
8,G022331,Shadow of Island,Xbox Series X/S,Console,Microsoft,9,Action-Adventure,2024,Capcom,Capcom,...,0,0,0,0,17.7,41.7,1,713CBECB,NaN,8724
9,G005473,FIFA 2025,Mobile (Android),Mobile,Google,0,Sports,2020,CD Projekt,CD Projekt,...,0,0,0,0,21.2,75.3,1,4D440F29,NaN,12060

In [6]:
train.dtypes

game_id                                   str
title                                     str
platform                                  str
platform_type                             str
platform_maker                            str
platform_generation                     int64
genre                                     str
year                                    int64
publisher                                 str
developer                                 str
publisher_region                          str
publisher_tier                            str
esrb_rating                               str
metacritic_score                      float64
user_score                            float64
critic_review_count                   float64
user_review_count                     float64
estimated_revenue_million_usd         float64
launch_price_usd                      float64
is_sequel                               int64
online_multiplayer                      int64
dlc_released                            int64
microtransactions                       int64
loot_boxes                              int64
game_pass_available                     int64
vr_support                              int64
goty_nominated                          int64
goty_won                                int64
how_long_to_beat_main_hrs             float64
how_long_to_beat_completionist_hrs    float64
publisher_is_developer                  int64
internal_build_id                         str
marketing_campaign_type                   str
day_one_patch_size_mb                   int64
dtype: object

In [7]:
train.isnull().sum()

game_id                                  0
title                                    0
platform                                 0
platform_type                            0
platform_maker                           0
platform_generation                      0
genre                                    0
year                                     0
publisher                                0
developer                                0
publisher_region                         0
publisher_tier                           0
esrb_rating                              0
metacritic_score                      6000
user_score                               0
critic_review_count                   6000
user_review_count                     6000
estimated_revenue_million_usd            0
launch_price_usd                         0
is_sequel                                0
online_multiplayer                       0
dlc_released                             0
microtransactions                        0
loot_boxes                               0
game_pass_available                      0
vr_support                               0
goty_nominated                           0
goty_won                                 0
how_long_to_beat_main_hrs                0
how_long_to_beat_completionist_hrs       0
publisher_is_developer                   0
internal_build_id                        0
marketing_campaign_type               9995
day_one_patch_size_mb                    0
dtype: int64

In [8]:
train.marketing_campaign_type = train.marketing_campaign_type.fillna('None')
train.isnull().sum()

game_id                                  0
title                                    0
platform                                 0
platform_type                            0
platform_maker                           0
platform_generation                      0
genre                                    0
year                                     0
publisher                                0
developer                                0
publisher_region                         0
publisher_tier                           0
esrb_rating                              0
metacritic_score                      6000
user_score                               0
critic_review_count                   6000
user_review_count                     6000
estimated_revenue_million_usd            0
launch_price_usd                         0
is_sequel                                0
online_multiplayer                       0
dlc_released                             0
microtransactions                        0
loot_boxes                               0
game_pass_available                      0
vr_support                               0
goty_nominated                           0
goty_won                                 0
how_long_to_beat_main_hrs                0
how_long_to_beat_completionist_hrs       0
publisher_is_developer                   0
internal_build_id                        0
marketing_campaign_type                  0
day_one_patch_size_mb                    0
dtype: int64

In [9]:
X = train.drop('estimated_revenue_million_usd',axis='columns')
y = train.estimated_revenue_million_usd

In [10]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [12]:
import re

KNOWN_FRANCHISES = [
    "Call of Duty",
    "The Witcher",
    "Dark Souls",
    "Final Fantasy",
    "God of War",
    "No Man's Sky",
    "Red Dead Redemption",
    "Grand Theft Auto",
    "MLB The Show",
    "Need for Speed",
    "Rainbow Six",
    "Counter-Strike",
    "Assassin's Creed",
    "Ghost Recon",
    "Metal Gear",
    "Devil May Cry",
    "Super Mario",
    "Batman",
    "Halo",
    "FIFA",
    "NBA",
    "NHL",
    "Madden",
    "Overwatch",
    "Battlefield",
    "Titanfall",
    "Minecraft",
    "Doom",
    "UFC",
    "F1",
    "WWE",
    "eFootball"
]

In [13]:
def extract_franchise(title):
    title_lower = title.lower()

    # Match known multi-word franchises first
    for franchise in sorted(KNOWN_FRANCHISES, key=len, reverse=True):
        if title_lower.startswith(franchise.lower()):
            return franchise

    # Remove years
    title = re.sub(r"\b(19|20)\d{2}\b", "", title)

    # Remove standalone sequel numbers
    title = re.sub(r"\b\d+\b", "", title)

    # Remove edition words
    remove_words = {
        "Remastered",
        "Ultimate",
        "Definitive",
        "Edition",
        "Complete",
        "Collection",
        "Evolved",
        "Reloaded",
        "Enhanced"
    }

    words = [w for w in title.split() if w not in remove_words]

    # Fallback: first word
    return words[0].strip(":")

In [14]:
sample = [
    "FIFA 2025",
    "Overwatch 6",
    "Batman: Arkham Valley",
    "The Witcher 2: Reckoning",
    "No Man's Sky Evolved",
    "Call of Duty Black Ops",
    "Dark Souls III",
    "MLB The Show 2026"
]

for s in sample:
    print(s, " --> ", extract_franchise(s))

FIFA 2025  -->  FIFA
Overwatch 6  -->  Overwatch
Batman: Arkham Valley  -->  Batman
The Witcher 2: Reckoning  -->  The Witcher
No Man's Sky Evolved  -->  No Man's Sky
Call of Duty Black Ops  -->  Call of Duty
Dark Souls III  -->  Dark Souls
MLB The Show 2026  -->  MLB The Show

In [15]:
X_train["franchise"] = X_train["title"].apply(extract_franchise)

In [16]:
print(X_train["franchise"].value_counts().head(30))

franchise
Doom              779
Dark              777
Shadow            771
Metal Gear        717
Rise              706
Halo              704
Batman            693
God               628
The               619
Devil             603
Dragon            430
FIFA              372
MLB The Show      368
NBA               359
UFC               359
NHL               353
F1                353
Final Fantasy     346
Rainbow Six       344
Call of Duty      333
Titanfall         330
PGA               330
Battlefield       320
Overwatch         318
eFootball         313
Counter-Strike    310
Madden            303
Super             302
Valorant          295
Apex              295
Name: count, dtype: int64

In [17]:
X_test["franchise"] = X_test["title"].apply(extract_franchise)

In [18]:
cat_features = X_train.select_dtypes(include=['object','category']).columns.tolist()
cat_features

C:\Users\HP\AppData\Local\Temp\ipykernel_13296\884961373.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = X_train.select_dtypes(include=['object','category']).columns.tolist()

['game_id',
 'title',
 'platform',
 'platform_type',
 'platform_maker',
 'genre',
 'publisher',
 'developer',
 'publisher_region',
 'publisher_tier',
 'esrb_rating',
 'internal_build_id',
 'marketing_campaign_type',
 'franchise']

In [19]:
y_test_log = np.log1p(y_test)
y_train_log = np.log1p(y_train)
y_train_log.shape

(30000,)

In [20]:
model1 = CatBoostRegressor(
    iterations=600,
    learning_rate=0.05,
    depth=6,
    loss_function='RMSE',
    random_seed=42,
    verbose=100,
    cat_features = cat_features
)

model1.fit(
    X_train,
    y_train,
    cat_features=cat_features
)

0:	learn: 1004.3686571	total: 299ms	remaining: 2m 58s
100:	learn: 762.8446817	total: 6.79s	remaining: 33.5s
200:	learn: 744.2568492	total: 13.3s	remaining: 26.5s
300:	learn: 731.0369728	total: 21s	remaining: 20.9s
400:	learn: 720.2866984	total: 31.2s	remaining: 15.5s
500:	learn: 711.8656380	total: 39.4s	remaining: 7.79s
599:	learn: 703.4674129	total: 47.3s	remaining: 0us

CatBoostRegressor(cat_features=['game_id', 'title', 'platform', 'platform_type', 'platform_maker', 'genre', 'publisher', 'developer', 'publisher_region', 'publisher_tier', 'esrb_rating', 'internal_build_id', 'marketing_campaign_type', 'franchise'], depth=6, iterations=600, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [21]:
model2 = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function='RMSE',
    random_seed=42,
    verbose=100,
    cat_features = cat_features
)

model2.fit(
    X_train,
    y_train_log,
    cat_features=cat_features
)

0:	learn: 1.8144256	total: 65.3ms	remaining: 32.6s
100:	learn: 0.7152980	total: 7.27s	remaining: 28.7s
200:	learn: 0.7022495	total: 15.2s	remaining: 22.6s
300:	learn: 0.6948031	total: 23.2s	remaining: 15.3s
400:	learn: 0.6889152	total: 31.9s	remaining: 7.88s
499:	learn: 0.6839343	total: 40.6s	remaining: 0us

CatBoostRegressor(cat_features=['game_id', 'title', 'platform', 'platform_type', 'platform_maker', 'genre', 'publisher', 'developer', 'publisher_region', 'publisher_tier', 'esrb_rating', 'internal_build_id', 'marketing_campaign_type', 'franchise'], depth=6, iterations=500, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [22]:
model1_pred = model1.predict(X_test)
model1_pred = np.clip(model1_pred,0,None)
model1_pred_log = np.log1p(model1_pred)
print(y_test[:20])
print(model1_pred[:20])
print(y_test_log[:20])
print(model1_pred_log[:20])

32823     577.36
16298     467.02
28505    1165.64
6689       62.81
26893       0.00
36572    1209.61
12335     240.86
29591     154.61
18948    3117.85
31067     683.40
22241       0.00
13787    1929.78
5128      547.40
9125      437.24
35041     217.82
3510      392.18
16441     279.54
19463      66.15
26283      87.55
36216       0.00
Name: estimated_revenue_million_usd, dtype: float64
[ 422.32199307  186.20774846  507.37173849  165.25643719    0.
  912.620718    192.20080505  343.31190498 1398.16804054 1163.29305902
    0.          895.50871081  758.19390025  686.5032036   315.56517675
  932.1021539   179.81379431  209.94934828  608.46558926    0.        ]
32823    6.360197
16298    6.148511
28505    7.061883
6689     4.155910
26893    0.000000
36572    7.098880
12335    5.488359
29591    5.047353
18948    8.045220
31067    6.528543
22241    0.000000
13787    7.565679
5128     6.307005
9125     6.082767
35041    5.388249
3510     5.974268
16441    5.636716
19463    4.206929
26283    4.483567
36216    0.000000
Name: estimated_revenue_million_usd, dtype: float64
[6.0481331  5.23221895 6.23121295 5.1135314  0.         6.81741552
 5.26373009 5.84154795 7.24363308 7.05986937 0.         6.79850801
 6.63225721 6.53306649 5.75752915 6.83851468 5.19746774 5.35161805
 6.41258249 0.        ]

In [23]:
model2_pred_log = model2.predict(X_test)
model2_pred = np.expm1(model2_pred_log)
print(y_test[:20])
print(model2_pred[:20])
print(y_test_log[:20])
print(model2_pred_log[:20])

32823     577.36
16298     467.02
28505    1165.64
6689       62.81
26893       0.00
36572    1209.61
12335     240.86
29591     154.61
18948    3117.85
31067     683.40
22241       0.00
13787    1929.78
5128      547.40
9125      437.24
35041     217.82
3510      392.18
16441     279.54
19463      66.15
26283      87.55
36216       0.00
Name: estimated_revenue_million_usd, dtype: float64
[ 3.37179916e+02  1.51037206e+02  3.67947266e+02  1.50691362e+02
 -7.71914996e-02  4.94442150e+02  8.38598482e+01  2.02217131e+02
  1.15816722e+03  9.17606430e+02  8.09176775e-02  7.35136405e+02
  5.35149033e+02  6.07325406e+02  1.81502947e+02  6.94594444e+02
  1.34568695e+02  1.72001341e+02  5.23438088e+02 -9.77266844e-03]
32823    6.360197
16298    6.148511
28505    7.061883
6689     4.155910
26893    0.000000
36572    7.098880
12335    5.488359
29591    5.047353
18948    8.045220
31067    6.528543
22241    0.000000
13787    7.565679
5128     6.307005
9125     6.082767
35041    5.388249
3510     5.974268
16441    5.636716
19463    4.206929
26283    4.483567
36216    0.000000
Name: estimated_revenue_million_usd, dtype: float64
[ 5.82357805  5.02412527  5.91065372  5.02184794 -0.08033354  6.2054506
  4.44100105  5.31427502  7.05545711  6.82285777  0.07781038  6.60141543
  6.28441217  6.41070995  5.20676632  6.54476679  4.90947848  5.15329934
  6.26232738 -0.00982073]

In [24]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score,
    root_mean_squared_log_error
)

In [25]:
print("CatBoost 1")
print("MAE :", mean_absolute_error(y_test, model1_pred))
print("MSE :", mean_squared_error(y_test, model1_pred))
print("RMSE:", root_mean_squared_error(y_test, model1_pred))
print("R²  :", r2_score(y_test, model1_pred))
print("RMSLE :", root_mean_squared_error(y_test_log,model1_pred_log))

CatBoost 1
MAE : 361.8567689239273
MSE : 539854.2577714069
RMSE: 734.7477511169442
R²  : 0.4517132709531778
RMSLE : 1.0781947399067293

In [26]:
print("CatBoost 2")
print("MAE :", mean_absolute_error(y_test, model2_pred))
print("MSE :", mean_squared_error(y_test, model2_pred))
print("RMSE:", root_mean_squared_error(y_test, model2_pred))
print("R²  :", r2_score(y_test, model2_pred))
print("RMSLE :", root_mean_squared_error(y_test_log,model2_pred_log))

CatBoost 2
MAE : 336.3178018115009
MSE : 590988.433874996
RMSE: 768.7577211807346
R²  : 0.3997803839660893
RMSLE : 0.7068087990640147

In [27]:
from sklearn.metrics import root_mean_squared_log_error

model2_pred = np.clip(model2_pred, 0, None)
score = root_mean_squared_log_error(y_test, model2_pred)
print(score)

0.7065250096599134

In [28]:
final_pred = 0.5*model1_pred + 0.5*model2_pred
final_pred_log = np.log1p(final_pred)

In [29]:
print("Final")
print("MAE :", mean_absolute_error(y_test, final_pred))
print("MSE :", mean_squared_error(y_test, final_pred))
print("RMSE:", root_mean_squared_error(y_test, final_pred))
print("R²  :", r2_score(y_test, final_pred))
print("RMSLE :", root_mean_squared_error(y_test_log,final_pred_log))

Final
MAE : 342.7429481269439
MSE : 552754.2408308836
RMSE: 743.4744385860778
R²  : 0.4386117914063872
RMSLE : 0.9156748940452872

In [30]:
X["franchise"] = X["title"].apply(extract_franchise)
X.shape

(40000, 34)

In [31]:
test.shape

(10000, 33)

In [32]:
test["franchise"] = test["title"].apply(extract_franchise)
test.shape

(10000, 34)

In [33]:
y_log = np.log1p(y)
y_log

0        5.572610
1        6.560903
2        7.425495
3        4.693822
4        6.509022
           ...
39995    8.364587
39996    0.000000
39997    0.000000
39998    6.638398
39999    3.663305
Name: estimated_revenue_million_usd, Length: 40000, dtype: float64

In [34]:
cat_features = X.select_dtypes(include=['object','category']).columns.tolist()
cat_features

C:\Users\HP\AppData\Local\Temp\ipykernel_13296\1138654257.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = X.select_dtypes(include=['object','category']).columns.tolist()

['game_id',
 'title',
 'platform',
 'platform_type',
 'platform_maker',
 'genre',
 'publisher',
 'developer',
 'publisher_region',
 'publisher_tier',
 'esrb_rating',
 'internal_build_id',
 'marketing_campaign_type',
 'franchise']

In [35]:
model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    loss_function='RMSE',
    random_seed=42,
    verbose=100,
    cat_features = cat_features
)

In [36]:
model.fit(
    X,
    y_log,
    cat_features=cat_features
)

0:	learn: 1.8154318	total: 92.3ms	remaining: 46.1s
100:	learn: 0.7195023	total: 10.6s	remaining: 41.9s
200:	learn: 0.7060475	total: 21.1s	remaining: 31.4s
300:	learn: 0.6985892	total: 31.5s	remaining: 20.9s
400:	learn: 0.6942393	total: 42.4s	remaining: 10.5s
499:	learn: 0.6900639	total: 54s	remaining: 0us

CatBoostRegressor(cat_features=['game_id', 'title', 'platform', 'platform_type', 'platform_maker', 'genre', 'publisher', 'developer', 'publisher_region', 'publisher_tier', 'esrb_rating', 'internal_build_id', 'marketing_campaign_type', 'franchise'], depth=6, iterations=500, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [37]:
test.isnull().sum()

game_id                                  0
title                                    0
platform                                 0
platform_type                            0
platform_maker                           0
platform_generation                      0
genre                                    0
year                                     0
publisher                                0
developer                                0
publisher_region                         0
publisher_tier                           0
esrb_rating                              0
metacritic_score                      1500
user_score                               0
critic_review_count                   1500
user_review_count                     1500
launch_price_usd                         0
is_sequel                                0
online_multiplayer                       0
dlc_released                             0
microtransactions                        0
loot_boxes                               0
game_pass_available                      0
vr_support                               0
goty_nominated                           0
goty_won                                 0
how_long_to_beat_main_hrs                0
how_long_to_beat_completionist_hrs       0
publisher_is_developer                   0
internal_build_id                        0
marketing_campaign_type               2464
day_one_patch_size_mb                    0
franchise                                0
dtype: int64

In [38]:
test.marketing_campaign_type = test.marketing_campaign_type.fillna('None')
test.isnull().sum()

game_id                                  0
title                                    0
platform                                 0
platform_type                            0
platform_maker                           0
platform_generation                      0
genre                                    0
year                                     0
publisher                                0
developer                                0
publisher_region                         0
publisher_tier                           0
esrb_rating                              0
metacritic_score                      1500
user_score                               0
critic_review_count                   1500
user_review_count                     1500
launch_price_usd                         0
is_sequel                                0
online_multiplayer                       0
dlc_released                             0
microtransactions                        0
loot_boxes                               0
game_pass_available                      0
vr_support                               0
goty_nominated                           0
goty_won                                 0
how_long_to_beat_main_hrs                0
how_long_to_beat_completionist_hrs       0
publisher_is_developer                   0
internal_build_id                        0
marketing_campaign_type                  0
day_one_patch_size_mb                    0
franchise                                0
dtype: int64

In [39]:
y_pred_log = model.predict(test)
y_pred_log

array([3.18314843, 3.04981486, 4.13738302, ..., 6.75857926, 5.98521626,
       6.56528163], shape=(10000,))

In [40]:
y_pred = np.expm1(y_pred_log)
y_pred

array([ 23.12258232,  20.11143557,  61.63868263, ..., 860.41747248,
       396.50847639, 709.01183074], shape=(10000,))

In [41]:
output = pd.DataFrame({'game_id':test.game_id,'estimated_revenue_million_usd':y_pred})
output

      game_id  estimated_revenue_million_usd
0     G016973                      23.122582
1     G011036                      20.111436
2     G000593                      61.638683
3     G013281                      -0.140844
4     G004160                      57.724472
...       ...                            ...
9995  G047616                     462.946449
9996  G029677                      47.368553
9997  G036291                     860.417472
9998  G020861                     396.508476
9999  G003277                     709.011831

[10000 rows x 2 columns]

In [42]:
output.to_csv('submission-catboost-log.csv',index=False)